apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: flux-system
  labels:
    temp: label
spec:
  interval: 10m
  url:  https://kubernetes-sigs.github.io/metrics-server/
