apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kps
  namespace: flux-system
spec:
  targetNamespace: monitoring
  releaseName: kps
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
    namespace: flux-system
  interval: 10m
  install:
    createNamespace: true
  values:
    # Disable Alertmanager to save memory
    alertmanager:
      enabled: false
    grafana:
      enabled: true
      defaultDashboardsEnabled: false
      persistence:
        accessModes:
        - ReadWriteOnce
        enabled: true
        finalizers:
        - kubernetes.io/pvc-protection
        size: 10Gi
        storageClassName: longhorn
        type: sts
      service:
        nodePort: 31000
        type: NodePort

    prometheus:
      prometheusSpec:
        replicas: 1
        retention: 7d 
        resources:
          requests:
            cpu: 100m
            memory: 512Mi

    defaultRules:
      create: true

    kubeApiServer:
      enabled: false

    kubeEtcd:
      enabled: false

    kubeControllerManager:
      enabled: true

    kubeScheduler:
      enabled: false

    kubeProxy:
      enabled: false

    coreDns:
      enabled: false

    kubeStateMetrics:
      enabled: true

    prometheus-node-exporter:
      enabled: true
